apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: dotnet14824new
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dotnet14824new 
  name: dotnet14824new
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: dotnet14824new
    weight: 100 
